name: Release

on:
  push:
    tags: ['v*']

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Linux
    runs-on: rust-1.93-bookworm
    steps:
      - name: Install system dependencies
        run: apt-get update && apt-get install -y git nodejs npm musl-tools musl-dev

      - uses: https://data.forgejo.org/actions/checkout@v4

      - name: Add musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build x86_64-musl (static)
        run: cargo build --release --target x86_64-unknown-linux-musl -p prism-server -p prism-cli -p prism-importer

      - name: Create dist
        run: cargo xtask dist --target x86_64-unknown-linux-musl

      - name: Upload artifact
        uses: https://data.forgejo.org/actions/upload-artifact@v4
        with:
          name: dist-linux-x86_64-static
          path: dist/*.tar.gz

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Build aarch64
        run: |
          source $HOME/.cargo/env
          cargo build --release -p prism-server -p prism-cli -p prism-importer

      - name: Create dist
        run: |
          source $HOME/.cargo/env
          cargo xtask dist

      - name: Upload via scp
        env:
          ARTIFACT_SSH_KEY: ${{ secrets.ARTIFACT_SSH_KEY }}
          ARTIFACT_HOST: ${{ secrets.ARTIFACT_HOST }}
        run: |
          if [ -n "$ARTIFACT_SSH_KEY" ] && [ -n "$ARTIFACT_HOST" ]; then
            mkdir -p ~/.ssh
            echo "$ARTIFACT_SSH_KEY" > ~/.ssh/artifact_key
            chmod 600 ~/.ssh/artifact_key
            scp -o StrictHostKeyChecking=no -i ~/.ssh/artifact_key dist/*.tar.gz "$ARTIFACT_HOST"
            rm ~/.ssh/artifact_key
          else
            echo "Artifact upload skipped - ARTIFACT_SSH_KEY or ARTIFACT_HOST not configured"
            ls -la dist/
          fi

  build-windows:
    name: Build Windows
    runs-on: windows10msvc2022
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4

      - name: Install Rust
        run: |
          Invoke-WebRequest -Uri https://win.rustup.rs/x86_64 -OutFile rustup-init.exe
          .\rustup-init.exe -y
          $env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"

      - name: Build
        run: |
          $env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"
          cargo build --release -p prism-server -p prism-cli -p prism-importer

      - name: Create dist
        run: |
          $env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"
          cargo xtask dist --format zip

      - name: Upload via scp
        env:
          ARTIFACT_SSH_KEY: ${{ secrets.ARTIFACT_SSH_KEY }}
          ARTIFACT_HOST: ${{ secrets.ARTIFACT_HOST }}
        run: |
          if ($env:ARTIFACT_SSH_KEY -and $env:ARTIFACT_HOST) {
            $keyPath = "$env:USERPROFILE\.ssh\artifact_key"
            New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.ssh" | Out-Null
            $env:ARTIFACT_SSH_KEY | Out-File -FilePath $keyPath -Encoding ASCII
            scp -o StrictHostKeyChecking=no -i $keyPath dist\*.zip $env:ARTIFACT_HOST
            Remove-Item $keyPath
          } else {
            Write-Host "Artifact upload skipped - secrets not configured"
            Get-ChildItem dist\
          }

  create-release:
    name: Create Release
    needs: [build-linux]  # Only Linux can upload artifacts for now
    runs-on: rust-1.93-bookworm
    steps:
      - name: Install system dependencies
        run: apt-get update && apt-get install -y git nodejs npm

      - uses: https://data.forgejo.org/actions/checkout@v4

      - name: Download Linux artifact
        uses: https://data.forgejo.org/actions/download-artifact@v4
        with:
          name: dist-linux-x86_64-static
          path: artifacts

      - name: List artifacts
        run: ls -la artifacts/

      - name: Create checksums
        run: |
          cd artifacts
          sha256sum *.tar.gz > SHA256SUMS.txt
          cat SHA256SUMS.txt

      - name: Create release
        uses: https://data.forgejo.org/actions/forgejo-release@v2
        with:
          direction: upload
          tag: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_TOKEN }}
          release-dir: artifacts
          release-notes: |
            ## Prism ${{ github.ref_name }}

            ### Downloads

            | Platform | Architecture | File |
            |----------|--------------|------|
            | Linux | x86_64 (static/musl) | `prism-*-linux-x86_64-static.tar.gz` |

            ### Build from Source

            ```bash
            # macOS / Windows / other platforms
            cargo build --release -p prism-server -p prism-cli
            ```

            ### Checksums

            See `SHA256SUMS.txt` for file checksums.
