collection: .kibana
description: "Kibana saved objects"
backends:
  text:
    fields:
      - name: type
        type: string
        stored: true
        indexed: true
      - name: title
        type: string
        stored: true
        indexed: true
      - name: body
        type: string
        stored: true
        indexed: true
