collection: .kibana_analytics_9.5.0_001
description: Auto-created from Elasticsearch create-index request
backends:
  text:
    fields:
    - name: accessControl.owner
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: canvas-element.@created
      type: date
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: canvas-element.@timestamp
      type: date
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: canvas-element.content
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: canvas-element.help
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: canvas-element.image
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: canvas-element.name
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: canvas-workpad.@created
      type: date
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: canvas-workpad.@timestamp
      type: date
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: canvas-workpad.name
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: canvas-workpad-template.help
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: canvas-workpad-template.name
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: canvas-workpad-template.tags
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: canvas-workpad-template.template_key
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: coreMigrationVersion
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: created_at
      type: date
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: created_by
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.controlGroupInput
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.hits
      type: i64
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.kibanaSavedObjectMeta
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.optionsJSON
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.panelsJSON
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.refreshInterval
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.sections
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.timeFrom
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.timeRestore
      type: bool
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.timeTo
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: dashboard.version
      type: i64
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: event-annotation-group.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: event-annotation-group.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: graph-workspace.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: graph-workspace.kibanaSavedObjectMeta
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: graph-workspace.legacyIndexPatternRef
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: graph-workspace.numLinks
      type: i64
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: graph-workspace.numVertices
      type: i64
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: graph-workspace.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: graph-workspace.version
      type: i64
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: graph-workspace.wsState
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: index-pattern.name
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: index-pattern.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: index-pattern.type
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: lens.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: lens.state
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: lens.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: lens.visualizationType
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: lens-ui-telemetry.count
      type: i64
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: lens-ui-telemetry.date
      type: date
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: lens-ui-telemetry.name
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: lens-ui-telemetry.type
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: links.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: links.links
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: links.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: managed
      type: bool
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: map.bounds
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: map.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: map.layerListJSON
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: map.mapStateJSON
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: map.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: map.uiStateJSON
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: map.version
      type: i64
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: markdown.content
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: markdown.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: markdown.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: namespace
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: namespaces
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: originId
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: query.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: query.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: query.titleKeyword
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: references.id
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: references.name
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: references.type
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: search.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: search.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: search-session.created
      type: date
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: search-session.realmName
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: search-session.realmType
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: search-session.sessionId
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: search-session.status
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: search-session.username
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: type
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: typeMigrationVersion
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: updated_at
      type: date
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    - name: updated_by
      type: string
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: visualization.description
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: visualization.kibanaSavedObjectMeta
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: visualization.title
      type: text
      stored: true
      indexed: true
      tokenizer: null
      tokenizer_options: null
    - name: visualization.version
      type: i64
      stored: true
      indexed: false
      tokenizer: null
      tokenizer_options: null
    bm25_k1: null
    bm25_b: null
indexing:
  batch_size: 0
  commit_interval_secs: 0
  worker_threads: 0
quota:
  max_documents: null
  max_size_mb: null
embedding_generation: null
facets: null
boosting: null
storage:
  type: local
  path: null
system_fields:
  indexed_at: true
  document_boost: false
hybrid: null
replication: null
reranking: null
ilm_policy: null
